name: sip_mangsang
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  quickalert: ^1.0.2
  syncfusion_flutter_datepicker: ^23.2.4
  intl: ^0.18.1
  http: ^1.1.0
  top_snackbar_flutter: ^3.1.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.7
  get_it: ^7.6.4
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  awesome_select: ^6.0.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  device_info_plus: ^9.1.1
  document_file_save_plus: ^2.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-silap.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo-silap.png"
  windows:
    generate: true
    image_path: "assets/images/logo-silap.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo-silap.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/
    - assets/images/
    - assets/svg/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
